def remote = [:]
agentName = 'macos'
agentAddress = '192.168.0.196'

pipeline {
	agent { label agentName }
	stages {
        stage('Build') {
            steps {
                sh 'xcodebuild -project SampleUnitTesting.xcodeproj -scheme SampleUnitTesting -destination "platform=iOS Simulator,name=iPhone 11,OS=14.3"'
            }
        }
        stage('Lint') {
            steps {
                sh 'swiftlint'
            }
        }
        stage('Tests') {
            steps {
                sh 'xcodebuild test -project SampleUnitTesting.xcodeproj -scheme SampleUnitTestingXCTests -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=14.3"'
            }
        }
        stage('Horusec') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'macos', passwordVariable: 'pass', usernameVariable: 'user')]) {
                        remote.name = "$user"
                        remote.host = agentAddress
                        remote.user = "$user"
                        remote.password = "$pass"
                        remote.allowAnyHosts = true
                        remote.pty = true    
                    }
                    sshCommand remote: remote, command: 'curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest' , sudo: true
                    sh 'horusec start -a aec4312b-37e8-4188-ae77-135d23dc208e -p .'
                }

            }
        }
    }
}